// Generated by nitro

// App Config
import type { Defu } from 'defu'



type UserAppConfig = Defu<{}, []>

declare module "nitropack/types" {
  interface AppConfig extends UserAppConfig {}
  interface NitroRuntimeConfig {
   serverAccessToken: string,

   vapidPublicKey: string,

   vapidPrivateKey: string,

   vapidEmail: string,
  }
}
export {}